# Generated by Django 4.2.11 on 2024-08-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutLogger', '0002_exercise_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
