# Generated by Django 4.2.11 on 2024-08-18 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutLogger', '0004_exercise_lowerrange_exercise_upperrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='RPE',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
