# Generated by Django 4.2.11 on 2024-08-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutLogger', '0006_remove_exercise_rpe_set_rpe'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='recWeight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
