# Generated by Django 4.2.11 on 2024-08-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutLogger', '0007_exercise_recweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='recWeight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
