# Generated by Django 4.2.11 on 2024-06-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_delete_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciselog',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='workout',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseLog',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
